apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: omnifood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: salah529/omnifood:latest
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: omnifood
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 4173
      targetPort: 4173
