name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout repo
            - name: Checkout code
              uses: actions/checkout@v4

            # Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            # Build Frontend
            - name: Build Frontend
              run: |
                  npm ci
                  npm run build

            # Build Docker image
            - name: Build Docker images
              run: |
                  docker build -t salah529/omnifood:latest .

            # Push Docker image
            - name: Push Docker images
              if: github.ref == 'refs/heads/main'
              env:
                  DOCKER_USER: ${{ secrets.DOCKER_USER }}
                  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
              run: |
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                  docker push $DOCKER_USER/omnifood:latest
